### ISSUE TITLE
large string in translation

### ISSUE THREAD

**Issue by nikoss** [ppareit/swiftp#105]
Hi, when creating the Greek translation for swiftp, I came across a very large string:
string name="help_dlg_message"

From a translators point of view, it would be nicer if this string was broken down 
to, at least, 1 string per paragraph.
This would help future translators, but also existing translations (*).

(*)For example, if you decide to make a small change, in the future,
with the current string, it would be time consuming for the translator to spot it,
and adjust the translation.
Multiply that time to the number of translator's... you get my point, I hope.

Thanks

**Comment by ppareit** [comment]
Good point, never looked at is in this way.

I will break this string in multiple strings. Won't do this now, but will wait till I make change to that string.
