### ISSUE TITLE
Log commands

### ISSUE THREAD

**Issue by ppareit** [ppareit/swiftp#147]
It would be great if the app had a main window where you could see the log of all operations: someone connecting, authenticating, running commands like list, get, put, etc.

_See email from  Elijah on 9/12/2019_

**Comment by Xavron** [comment]
I have a test of this working atm. Intend to fully implement and create a pull request soon enough.

**Comment by Xavron** [comment]
Pull request added: https://github.com/ppareit/swiftp/pull/227

**Comment by ppareit** [comment]
Pull fixes this
