### ISSUE TITLE
No free version on Google

### ISSUE THREAD

**Issue by jidanni** [ppareit/swiftp#149]
On https://f-droid.org/packages/be.ppareit.swiftp_free/ we read
> The name Demo in the launcher just means that it corresponds to the free version on Google. 

However there is no such version on Google.

**Comment by jidanni** [comment]
See also https://github.com/ppareit/swiftp/issues/121 . So the wording needs to be changed.

Too bad for users who do not wish to use F-droid.

**Comment by jidanni** [comment]
(Yes I was able to do ftp gets, but for some reason at a much lower "baud rate" than net.xnano.android.ftpserver .)

**Comment by ppareit** [comment]
Yes, use the free version at f-droid.
