### ISSUE TITLE
Integer Overflow in CmdLIST.java

### ISSUE THREAD

**Issue by thomric2** [ppareit/swiftp#152]
The LIST command does not properly change its output when a file's modified date is within the last 6 months or not. Turns out the issue is the creation of MS_IN_SIX_MONTHS. The constants in the expression need to be cast as Long to properly create the constant.
`public final static long MS_IN_SIX_MONTHS = 6L * 30L * 24L * 60L * 60L * 1000L;`

**Comment by ppareit** [comment]
This seems to be fixed in 2014, see commit a04cba1b695e00669d8f8fb81d668c96626bee4b. What did I miss?

**Comment by ashutoshgngwr** [comment]
@ppareit backward compatibility with versions older than https://github.com/ppareit/swiftp/commit/a04cba1b695e00669d8f8fb81d668c96626bee4b :rofl:

**Comment by ppareit** [comment]
Then I need to throw my hands up in the air..
