### ISSUE TITLE
Non-compliant HASH response

### ISSUE THREAD

**Issue by matbech** [ppareit/swiftp#167]
The server (SwiFTP 3.1) returns this response for a HASH command:
```
HASH file.jpg
213 SHA-512 0-130341 bf69107115ac3666db2440ecf42c0525d39ad32e785d6d11bc98cc18fde3744849770457e80837022f99c5629c369f9e752b95827c7e3da23f99a5e4d7389d8e file.jpg
```

However, the HASH draft specifies:
```
      hash-response = hash-ok / error-response
      hash-ok       = "213" SP hashname SP 1*HEXDIGIT SP <pathname> CRLF
```
Reference: https://tools.ietf.org/html/draft-bryan-ftp-hash-08

Notice the range shouldn't be part of the HASH response.

**Comment by ppareit** [comment]
Yes, but this more recent draft
https://tools.ietf.org/html/draft-ietf-ftpext2-hash-03
specifies
`hash-ok       = "213" SP hashname SP start-point "-" end-point SP filehash SP <pathname> CRLF`
which to follow?

**Comment by matbech** [comment]
Oh yes, you are correct. Your implementation seems to fine in this regard.

**Comment by matbech** [comment]
I'm reopening this as "draft-ietf-ftpext2-hash-03" has been replaced by:
https://datatracker.ietf.org/doc/draft-bryan-ftpext-hash/

So the syntax in draft-bryan-ftpext-hash probably should be followed.
