### ISSUE TITLE
Android 11+ storage fixes needed

### ISSUE THREAD

**Issue by Xavron** [ppareit/swiftp#176]
The new storage changes still has issues with the app that I've been fixing this week. Not everything will be fixed, so this issue will not be fully resolved, but its fully working for me with my use as of today. 32GB with a backup application and its working great on Android 12.

Guessing you'll probably see it next week.  Need to refactor some code still :)

**Update:** All tests complete and green. Changes imminent.

**Comment by ppareit** [comment]
Good to hear. Lot of people will look forward to that! I'm looking forward to a pull request.
