### ISSUE TITLE
[fix included] Target of Android 13 will break notifications

### ISSUE THREAD

**Issue by Xavron** [ppareit/swiftp#181]
I'm just adding this as an issue for various reasons =)

But, on targeting of Android 13, the notifications will fail to show up. Otherwise, the app works as it was. This shows up with an error about user not allowing it instead of a check for permission error. Oh well.

Apparently, there's a breaking change to deal with but at least its simple enough. Note about it is in the following link.

https://developer.android.com/develop/ui/views/notifications/notification-permission

Fix needed (tested as working):

```
<manifest ...>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
```

MainActivity...

```
    @Override
    public void onCreate(Bundle savedInstanceState) {
        Cat.d("created");
        setTheme(FsSettings.getTheme());
        super.onCreate(savedInstanceState);

        if (!haveReadWritePermissions()) {
            requestReadWritePermissions();
        }

        if (!haveNotiPermissions()) {
            requestNotiPermissions();
        }
```

```
    private boolean haveNotiPermissions() {
        if (VERSION.SDK_INT >= 33) {
            return checkSelfPermission(POST_NOTIFICATIONS) == PERMISSION_GRANTED
                    && checkSelfPermission(POST_NOTIFICATIONS) == PERMISSION_GRANTED;
        } else {
            return true;
        }
    }

    private void requestNotiPermissions() {
        if (VERSION.SDK_INT < 33) return;
        String[] permissions = new String[]{POST_NOTIFICATIONS};
        requestPermissions(permissions, PERMISSIONS_REQUEST_CODE);
    }
```

**Comment by eakteam** [comment]
@Xavron -> https://github.com/ppareit/swiftp/issues/182

Regards

**Comment by Xavron** [comment]
PR #186

Should do it. I see that I had one other little change with notifications but quite sure its not necessary.
