### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by eakteam** [ppareit/swiftp#182]
This is great project but it seems that it have to much time without being upgraded and supporting latest Android versions like writing on external SD Card etc.
Is this dead or not?

@ppareit

**Comment by ppareit** [comment]
Yes. Updates happen as time permits. The pull request will be pulled. There are some big ones, and they need testing. Testing happens as time permits.

**Comment by eakteam** [comment]
> Yes. Updates happen as time permits. The pull request will be pulled. There are some big ones, and they need testing. Testing happens as time permits.

Thanks for your answer.

P.s there are a lot of deprecation things also, will they be covered by the update? And is there any ETA? Because if the update is big better to wait than to try to rewrite all changes ourself... 

Regards.

**Comment by eakteam** [comment]
@ppareit also please take a look at this: 

https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE
https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE

`Note: Starting in API level 33, this permission has no effect. If your app accesses other apps' media files, request one or more of these permissions instead: [READ_MEDIA_IMAGES](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES), [READ_MEDIA_VIDEO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO), [READ_MEDIA_AUDIO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_AUDIO). Learn more about the [storage permissions](https://developer.android.com/training/data-storage/shared/media#storage-permission) that are associated with media files.`

`Note: If your app targets [Build.VERSION_CODES.R](https://developer.android.com/reference/android/os/Build.VERSION_CODES#R) or higher, this permission has no effect.`#181 

Will this great project handle both those important changes?

**Comment by ppareit** [comment]
I'll look into checking and pulling the PR's during easter. I'll also go over the issues.

**Comment by Xavron** [comment]
> @ppareit also please take a look at this:
> 
> https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE
> 
> `Note: Starting in API level 33, this permission has no effect. If your app accesses other apps' media files, request one
> ...

That shouldn't be an issue with the target set at pre-sdk 33 as it is right now. Quite sure I did actually test a clean install on Android 13 that way.

Either way, when targeting Android 13 or not the following code fixes the older storage perm issue on app start or one way of doing it anyway (tested as working):

```
if (VERSION.SDK_INT < 33 /*denied on Android 13*/ && !haveReadWritePermissions()) {
    requestReadWritePermissions();
}
```

Since this was referenced here, am adding it here, although a new issue for it would probably be better. My bad :-D
