### ISSUE TITLE
[Suggestion] Limit anonymous user scope

### ISSUE THREAD

**Issue by Marevin** [ppareit/swiftp#224]
Since there is a feature to create users and set chroot for each, maybe the same option to limit anonymous users (they are already read-only, which is good)

**Comment by Xavron** [comment]
Seems like it should be done in CmdUSER (or CmdPASS where the anon login code is currently). A setting for user to specify the limit would be a good idea to go with it.

Should take no more than 15 minutes to do. I will probably do that and create a pull request in some months along with some other quick things if no one else does by then.

**Comment by Xavron** [comment]
Pull request added: https://github.com/ppareit/swiftp/pull/228

**Comment by ppareit** [comment]
Pulled in this fixes
