### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by ka223** [ppareit/swiftp#58]
Hi,

I tried to copy multiple files over ftp, but after a few seconds the connection is breaking down every time.

I tried with pcmanfm and filezilla und Android 5.0, 4.1.

Tested transfer mode aktiv and multiple connections to 1.

http://pastebin.com/JsCrT4zU

**Comment by ppareit** [comment]
Thanks ka223 for your report. I do sometimes have a lost connection but then it resumes as expected. I don't know how to reproduce your situation?

**Comment by ka223** [comment]
I tried to use ftp now with android 4.4 and filezilla without transferring any data.

For ex. by trying to access the camera folder, I receive any time a timeout and there are only 300 files in this folder.

**Comment by ka223** [comment]
A short update, some problem as before.

Using now cm 13, my wifi router is replaced too.
I hope some can give me a hint to figure out this annoying problem.

Device: Motorola G2
