### ISSUE TITLE
Can't recognize USB tethering

### ISSUE THREAD

**Issue by j3l11234** [ppareit/swiftp#59]
When the phone is on airplane mode(no wifi and mobile date)
the server can't start。
in the method，it does't detect the USB tethering.
I think we should  detect USB tethering as detect AP
![qq 20150426102832](https://cloud.githubusercontent.com/assets/5466555/7335642/566668d6-ebff-11e4-9915-f95f4bad3036.png)

**Comment by ppareit** [comment]
OK, I will try to fix this for the next version.

**Comment by ppareit** [comment]
See issue #56

**Comment by j3l11234** [comment]
╮(╯_╰)╭
thinks!
