### ISSUE TITLE
Automatic connect when on specific wifi

### ISSUE THREAD

**Issue by ppareit** [ppareit/swiftp#6]
An option to automatically start the FTP server when connected to a specific wifi network. (vergil)

**Comment by ibizaman** [comment]
Hello, thanks for this app! I am using it with an Icarus e-reader, works like a charm.
Seeing the last update date of this issue, I just wanted to know if it was foreseen to be implemented soon or not.

**Comment by ppareit** [comment]
@ibizaman This feature is in master now. I will try to release new version this week.

**Comment by ibizaman** [comment]
@ppareit awesome, thanks!
