### ISSUE TITLE
Can't find swiftp in Google Play Store

### ISSUE THREAD

**Issue by wp9015362** [ppareit/swiftp#60]
@ppareit :

I was googling for an open source FTP server for Android and came across swiftp.

The swiftp readme:

https://github.com/ppareit/swiftp/blob/master/README

has a link to the Google Play Store.

But it doesn't work.

I also can't find swiftp in the Google Play Store when searching it manually.

Has swiftp been removed from the Google Play Store?

Or is switfp discontinued?

Why isn't it available in the Play Store?

And are there any new open source alternatives available for swiftp?

Regards

**Comment by ppareit** [comment]
This should now be ok:
Free: https://play.google.com/store/apps/details?id=be.ppareit.swiftp_free
Supportive: https://play.google.com/store/apps/details?id=be.ppareit.swiftp

**Comment by wp9015362** [comment]
@ppareit :

Thanks. But already found an alternative open source app called "primitive ftpd" in the meantime which even supports SFTP, see:

https://github.com/wolpi/prim-ftpd
https://play.google.com/store/apps/details?id=org.primftpd

Regards
