### ISSUE TITLE
can MFMT use "touch -t"

### ISSUE THREAD

**Issue by j3l11234** [ppareit/swiftp#63]
╮(╯_╰)╭
now , it use File.setLastModified() , but i dosen't work because the permission problem.
I think we can try to use Runtime.getRuntime().exec();(need  root access)
I have done this and use it on my phone(Mi2s android5)
how do you think?

**Comment by ppareit** [comment]
I would prefer not to use root access for FTP Server.

**Comment by j3l11234** [comment]
╮(╯_╰)╭
maybe it can be optional...
