### ISSUE TITLE
SimpleDateFormat is not Thread Safe

### ISSUE THREAD

**Issue by gmembre** [ppareit/swiftp#65]
Hi, 

in the commit 1de190152d003c5f8652e2c94aed520c916410ea I saw that you put a SimpleDateFormat in a static field : as stated in the doc, http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
>
> Synchronization
>
> Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.

So you should not write : 
```java
static {
        df = new SimpleDateFormat("yyyyMMddhhmmss", Locale.US);
        df.setTimeZone(TimeZone.getTimeZone("UTC"));
}
```
but reinstanciates the SimpleDateFormat each time you need it.

**Comment by ppareit** [comment]
You are correct. While I could use use synchronized construct or ThreadLocal wrapper, I'm inclined to construct a local dateformat object to keep the code simple. OK for you?

**Comment by gmembre** [comment]
Yes, you can do : 
```java
public static String getFtpDate(long time){
   SimpleDateFormat df = new SimpleDateFormat("yyyyMMddhhmmss", Locale.US);
   df.setTimeZone(TimeZone.getTimeZone("UTC"));
   return df.format(new Date(time));
}
```

or even better if you to keep in one location the instanciation (note the `private`) : 
```java
private static SimpleDateFormat createSimpleDateFormat() {
   SimpleDateFormat df = new SimpleDateFormat("yyyyMMddhhmmss", Locale.US);
   df.setTimeZone(TimeZone.getTimeZone("UTC"));
   return df;
}

public static String getFtpDate(long time){
   return createSimpleDateFormat().format(new Date(time));
}
```

**Comment by ppareit** [comment]
OK, will make sure this is in the next release.

**Comment by ppareit** [comment]
Committed fix
