### ISSUE TITLE
Update https://ppareit.github.io/swiftp/

### ISSUE THREAD

**Issue by anewuser** [ppareit/swiftp#69]
https://ppareit.github.io/swiftp/ needs to be updated (there's a link to it on the README file/the text displayed on the frontpage of the project).

**Comment by ppareit** [comment]
That is correct.
You mean updating screenshots/history or more?

**Comment by anewuser** [comment]
Yes. It's good to keep the history updated (or remove it from that page) for people not ot think  that you've given up on the project. Thanks.
