### ISSUE TITLE
phone crash when files are transferred

### ISSUE THREAD

**Issue by herrdeh** [ppareit/swiftp#70]
On my slimkat 4.4.4, Huawei y300 I can make a connection to my Linux desktop, but when I try to actually transfer files, the phone will reliably crash.

This happens as well with other ftp servers and may therefore be an Android issue. As I cant expect help from the OS side - is there anything I can do? - Already tried several clean installs.

**Comment by ppareit** [comment]
Could it be that the phone heats up a lot when doing file transfers? Or is the crash at the very start of the file transfer?

**Comment by herrdeh** [comment]
Immideately after the file transfer is initiated - bang - reboot ... )-:

**Comment by ppareit** [comment]
On file transfers in both directions, on all folders?

**Comment by herrdeh** [comment]
wow - I checked with FileZilla - where both directions are working flawlessly.
So it must be crazy Nautilus FTP client - which seems to be a highly experimental piece of software anyway...

**Comment by herrdeh** [comment]
Checked with PCManFM file manager - everything working nicely.
Apologies for having bothered you  - everything is fine with your software. Thanks!

**Comment by ppareit** [comment]
Great to hear. I'll leave this issue open till I've tested with nautilus.
