### ISSUE TITLE
Hide notification icon

### ISSUE THREAD

**Issue by ppareit** [ppareit/swiftp#73]
Hide notification icon as an option. (by GaNi on 16/01/2016)

**Comment by Pandiora** [comment]
@ppareit This issue is from early 2016, when do you think you've time to fix some stuff - like this? It should be easy to fix and it annoys me too, since I want this app to stay silent.

**Comment by ppareit** [comment]
You are right.

**Comment by ppareit** [comment]
In master.

**Comment by Pandiora** [comment]
thank you
