### ISSUE TITLE
Exception at startup on Amazon FireTV

### ISSUE THREAD

**Issue by lemmy** [ppareit/swiftp#80]
swiftp on Amazon FireTV immediately crashes at startup:

E/AndroidRuntime( 7565): FATAL EXCEPTION: main
E/AndroidRuntime( 7565): Process: be.ppareit.swiftp_free, PID: 7565
E/AndroidRuntime( 7565): android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
E/AndroidRuntime( 7565):    at android.view.LayoutInflater.createView(LayoutInflater.java:637)
E/AndroidRuntime( 7565):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
E/AndroidRuntime( 7565):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:686)
E/AndroidRuntime( 7565):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
E/AndroidRuntime( 7565):    at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
E/AndroidRuntime( 7565):    at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
E/AndroidRuntime( 7565):    at android.preference.Preference.onCreateView(Preference.java:511)
E/AndroidRuntime( 7565):    at android.preference.Preference.getView(Preference.java:488)
E/AndroidRuntime( 7565):    at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
E/AndroidRuntime( 7565):    at android.widget.AbsListView.obtainView(AbsListView.java:2361)
E/AndroidRuntime( 7565):    at android.widget.ListView.makeAndAddView(ListView.java:1880)
E/AndroidRuntime( 7565):    at android.widget.ListView.fillDown(ListView.java:709)
E/AndroidRuntime( 7565):    at android.widget.ListView.fillFromTop(ListView.java:770)
E/AndroidRuntime( 7565):    at android.widget.ListView.layoutChildren(ListView.java:1689)
E/AndroidRuntime( 7565):    at android.widget.AbsListView.onLayout(AbsListView.java:2165)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime( 7565):    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime( 7565):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime( 7565):    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime( 7565):    at android.view.View.layout(View.java:16028)
E/AndroidRuntime( 7565):    at android.view.ViewGroup.layout(ViewGroup.java:5051)
E/AndroidRuntime( 7565):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2114)
E/AndroidRuntime( 7565):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1871)
E/AndroidRuntime( 7565):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1083)
E/AndroidRuntime( 7565):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5969)
E/AndroidRuntime( 7565):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:830)
E/AndroidRuntime( 7565):    at android.view.Choreographer.doCallbacks(Choreographer.java:643)
E/AndroidRuntime( 7565):    at android.view.Choreographer.doFrame(Choreographer.java:613)
E/AndroidRuntime( 7565):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:816)
E/AndroidRuntime( 7565):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 7565):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7565):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7565):    at android.app.ActivityThread.main(ActivityThread.java:5466)
E/AndroidRuntime( 7565):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7565):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7565):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
E/AndroidRuntime( 7565):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/AndroidRuntime( 7565): Caused by: java.lang.reflect.InvocationTa
I/AndroidRuntime( 7565): To Report FATAL to activityManagerService

**Comment by ppareit** [comment]
Thanks for the trace. Though, I'm unable to find the problem here. I need a trace in witch the process contains at least be.ppareit.swiftp. Do reopen if you can provide it. Letting the android system send me a debug report on FC will show up in my developer console, so that is also an option.
