### ISSUE TITLE
crashes when folder path not available

### ISSUE THREAD

**Issue by ka223** [ppareit/swiftp#82]
Hi,

I replaced my sdcard and the path changed.

It is not possible to start the ftp server or change the path (to the new sd card), the app is crashing.

Deleting app data would be a workaround. The problem is solved for me now, but ... JFYI

Thanks

**Comment by ppareit** [comment]
In version 2.13 (latest) I've made some changes to FsSettings::getChrootDir, this should fix exactly the FC you are seeing. Is it possible to send me the logcat output (filter on be.ppareit.swiftp and check for privacy) when the app crashes?

**Comment by ka223** [comment]
I have the newest play store version 2.12 installed. If you fixed this at 2.13, this bug is maybe obsolete ...

**Comment by ppareit** [comment]
I've published an update to the play store for the demo version. This update should be available in your location in several hours. Could you update and test to see if this bug is still there?

**Comment by ka223** [comment]
Version 2.13.1
If the selected folder is not available, it switches to the internal storage. 
It's working now ;)
