### ISSUE TITLE
Please display version number

### ISSUE THREAD

**Issue by Vrihub** [ppareit/swiftp#83]
There is no way to see the current version number from within the application (you have to go to android settings -> applications). Please display the version number in the "About..." screen, as almost all apps do.

**Comment by ppareit** [comment]
Yes, you are right. Next version will contain revamped About, Help and Feedback dialogs. It is somethings that has irritated me also.

I'll leave this open till this is fixed.

**Comment by Vrihub** [comment]
Thanks, though it took me some time to understand you have to scroll down the screen to see the info, when you click on "About" all you see is a full-screen logo, that looks like a bug at first :P
